# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Hello Universe!
author: STScI Notebook Dev
copyright: 2022-2024
logo: HelloUniverseLogo.png

html:
  google_analytics_id: 
  
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off
  timeout                   : -1    # timeout in seconds, -1 removes timeout restrictions

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/spacetelescope/hellouniverse  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  binderhub_url: ""
